### PR TITLE
Keep flags

### PR DESCRIPTION
**Pull request by luigifab**
When trying to create a debian package, I need to update the Makefile to make Lintian happy.
I also updated `install` section.
Not sure if it's good or not.

### CODE REVIEW

**Comment by raalkml** [comment]
I'll gladly take "Fix install directory": I never used "install" target, shame on me! Thank you.

The "Keep flags" does not do what it seems to do: if you want change to **extend** the built-in flags you *must* use the environment (`CFLAGS='-Werror' make`). Passing the flags in the make command line produces a different result (it'll override the defaults).

I believe you can just set them to whatever the package needs, overriding "-O3 -ggdb", using make command-line (like this: `$(MAKE) CFLAGS='-Werror'` in the debian/rules file), but I don't know what's needed for the Debian package linter to be happy. Can you please show how exactly did you make it complain?

**Comment by raalkml** [comment]
Cherry-picked "Fix install directory".

**Comment by luigifab** [comment]
By keeping the original flags:

```
[...]
   dh_auto_build
	make -j2 "INSTALL=install --strip-program=true"
make[1] : on entre dans le répertoire « /home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0 »
gcc -MM -o O/gpx.d gpx.c  -D_GNU_SOURCE
gcc -MM -o O/gpx2tiles.d gpx2tiles.c  -D_GNU_SOURCE
gcc -Wall -ggdb -O3   -c -o O/gpx2tiles.o  -I/usr/include/libxml2  -Wall -ggdb -O3 -D_GNU_SOURCE  gpx2tiles.c
gcc -Wall -ggdb -O3   -c -o O/gpx.o  -I/usr/include/libxml2  -Wall -ggdb -O3 -D_GNU_SOURCE  gpx.c
gcc -Wall -ggdb -O3  O/gpx2tiles.o O/gpx.o  -lgd -lxml2   -lm -lpthread -o gpx2tiles
make[1] : on quitte le répertoire « /home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0 »
   dh_auto_test
   create-stamp debian/debhelper-build-stamp
   dh_prep
   dh_auto_install --destdir=debian/gpx2tiles/
	make -j2 install DESTDIR=/home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0/debian/gpx2tiles AM_UPDATE_INFO_DIR=no "INSTALL=install --strip-program=true"
make[1] : on entre dans le répertoire « /home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0 »
install -d /home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0/debian/gpx2tiles/usr/bin/
install -m 0755 gpx2tiles /home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0/debian/gpx2tiles/usr/bin/
make[1] : on quitte le répertoire « /home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0 »
[...]
```
Lintian says:
```
I: gpx2tiles: hardening-no-bindnow usr/bin/gpx2tiles
N: 
N:   This package provides an ELF binary that lacks the "bindnow" linker flag.
N:   
N:   This is needed (together with "relro") to make the "Global Offset Table" (GOT) fully read-only. The bindnow feature trades startup time for improved
N:   security. Please consider enabling this feature or consider overriding the tag (possibly with a comment about why).
N:   
N:   If you use dpkg-buildflags, you may have to add hardening=+bindnow or hardening=+all to DEB_BUILD_MAINT_OPTIONS.
N:   
N:   The relevant compiler flags are set in LDFLAGS.
N: 
N:   Please refer to https://wiki.debian.org/Hardening for details.
N: 
N:   Visibility: info
N:   Show-Always: no
N:   Check: binaries/hardening
N: 
N:
I: gpx2tiles: hardening-no-fortify-functions usr/bin/gpx2tiles
N: 
N:   This package provides an ELF binary that lacks the use of fortified libc functions. Either there are no potentially unfortified functions called by any
N:   routines, all unfortified calls have already been fully validated at compile-time, or the package was not built with the default Debian compiler flags
N:   defined by dpkg-buildflags. If built using dpkg-buildflags directly, be sure to import CPPFLAGS.
N:   
N:   NB: Due to false-positives, Lintian ignores some unprotected functions (e.g. memcpy).
N: 
N:   Please refer to https://wiki.debian.org/Hardening and Bug#673112 for details.
N: 
N:   Visibility: info
N:   Show-Always: no
N:   Check: binaries/hardening
```

With the updated flags, lintian is ok, `dh_auto_build` says:
```
   dh_auto_build
	make -j2 "INSTALL=install --strip-program=true"
make[1] : on entre dans le répertoire « /home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0 »
gcc -MM -o O/gpx.d gpx.c -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE
gcc -MM -o O/gpx2tiles.d gpx2tiles.c -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE
gcc -g -O2 -ffile-prefix-map=/home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -ggdb -O3 -Wdate-time -D_FORTIFY_SOURCE=2  -c -o O/gpx2tiles.o  -I/usr/include/libxml2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -ffile-prefix-map=/home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -ggdb -O3 -D_GNU_SOURCE  gpx2tiles.c
gcc -g -O2 -ffile-prefix-map=/home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -ggdb -O3 -Wdate-time -D_FORTIFY_SOURCE=2  -c -o O/gpx.o  -I/usr/include/libxml2 -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -ffile-prefix-map=/home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -ggdb -O3 -D_GNU_SOURCE  gpx.c
gcc -Wl,-z,relro -Wl,-z,now -Wall -ggdb -O3  O/gpx2tiles.o O/gpx.o  -lgd -lxml2   -lm -lpthread -o gpx2tiles
make[1] : on quitte le répertoire « /home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0 »
   dh_auto_test
   create-stamp debian/debhelper-build-stamp
   dh_prep
   dh_auto_install --destdir=debian/gpx2tiles/
	make -j2 install DESTDIR=/home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0/debian/gpx2tiles AM_UPDATE_INFO_DIR=no "INSTALL=install --strip-program=true"
make[1] : on entre dans le répertoire « /home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0 »
install -d /home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0/debian/gpx2tiles/usr/bin/
install -m 0755 gpx2tiles /home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0/debian/gpx2tiles/usr/bin/
make[1] : on quitte le répertoire « /home/fabrice/gpx2tiles/debian/builder/gpx2tiles-1.0.0 »
```

In both cases, I use the following `debian/rules`;
```
#!/usr/bin/make -f

export DEB_BUILD_MAINT_OPTIONS = hardening=+all

%:
	dh $@

```

I don't understand what I did in the _makefile_... 😄

**Comment by raalkml** [comment]
While understand what you did to the Makefile, I must admit I don't get it how to make a Debian package: I only ever use `debuild -- binary` on whatever `apt-get source` downloads.
I pushed whatever I managed to collect to build it in the **debian** branch.

Could you please try the master (or the "debian") if it is enough to build a package for you?

**Comment by luigifab** [comment]
In this archive you will found 3 scripts that build packages for Debian, Ubuntu, Fedora and openSUSE.
This is a derivate work from scripts used for my packages.
[gpx2tiles.tar.gz](https://github.com/raalkml/gpx2tiles/files/7921186/gpx2tiles.tar.gz)

I tested the new Makefile from master, it seems to work.

If you want to include your software in official repositories, you will need a manpage (like this [example](https://gist.githubusercontent.com/luigifab/876f3309fcd45227bd60d14894d40e18/raw/63e67549a0b1b0c2704fa4a97649a970ef920c8f/awf-gtk2.1), [online editor](https://roperzh.github.io/grapse/)), and a release.

**Pull request closed without merging**
